---
  app:
    name: "data-science"
    banner: "Dtp.Labs!"

  
  # Diretorios e padrão de nome dos arquivos que serão processados
  input:
    path: './data/'
    filename: 'biometria-tse-dataprev.csv'
    type: 'csv'
  

  output:
    path: './saida/'
    reportname: 'relatorio_geral.html'
    