---
  - name: Default | Install default packages
    apt:
      name: 
        - git
        - software-properties-common
        - build-essential
        - unzip 
        - curl
        - htop
        - wget
        - python3-pip
      update_cache: true
      state: present
    tags:
      - packages

  - include: pip.yml