---
- name: Configure an python enviroment, for data science
  hosts: 127.0.0.1
  connection: local
  become: yes
  become_user: root
  become_method: sudo
  vars_files:
    - vars/main.yml

  roles:
  - default
  - application